
import React, { useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Award, Eye, Plus } from 'lucide-react';
import CertificateGenerator from '@/components/certificates/CertificateGenerator';
import CertificatesList from '@/components/certificates/CertificatesList';
import RoleGuard from '@/components/common/RoleGuard';

const CertificatesModule = () => {
  const { user } = useAuth();
  const [activeTab, setActiveTab] = useState('list');

  const getPageTitle = () => {
    switch (user?.role) {
      case 'principal':
        return 'Certificate Generation';
      case 'school_owner':
        return 'View Certificates';
      case 'edufam_admin':
        return 'Certificate Management';
      default:
        return 'Certificates';
    }
  };

  const getPageDescription = () => {
    switch (user?.role) {
      case 'principal':
        return 'Generate academic certificates for students at the end of the academic year';
      case 'school_owner':
        return 'View all certificates generated by your school';
      case 'edufam_admin':
        return 'Manage certificates across all schools in the system';
      default:
        return 'Academic certificates management';
    }
  };

  const canGenerate = user?.role === 'principal' || user?.role === 'edufam_admin';

  return (
    <RoleGuard allowedRoles={['principal', 'school_owner', 'edufam_admin']} requireSchoolAssignment={user?.role !== 'edufam_admin'}>
      <div className="container mx-auto p-6 space-y-8">
        {/* Header */}
        <div className="text-center space-y-4">
          <div className="flex items-center justify-center space-x-3">
            <div className="p-3 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full">
              <Award className="h-8 w-8 text-white" />
            </div>
            <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
              {getPageTitle()}
            </h1>
          </div>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            {getPageDescription()}
          </p>
        </div>

        {/* Content */}
        {canGenerate ? (
          <Tabs value={activeTab} onValueChange={setActiveTab}>
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger value="list" className="flex items-center gap-2">
                <Eye className="h-4 w-4" />
                View Certificates
              </TabsTrigger>
              <TabsTrigger value="generate" className="flex items-center gap-2">
                <Plus className="h-4 w-4" />
                Generate New
              </TabsTrigger>
            </TabsList>

            <TabsContent value="list" className="space-y-6">
              <CertificatesList />
            </TabsContent>

            <TabsContent value="generate" className="space-y-6">
              <CertificateGenerator />
            </TabsContent>
          </Tabs>
        ) : (
          // School owners can only view certificates
          <CertificatesList />
        )}

        {/* Info Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card className="border-0 shadow-lg bg-gradient-to-br from-blue-50 to-blue-100">
            <CardContent className="p-6">
              <div className="flex items-center space-x-3">
                <Award className="h-8 w-8 text-blue-600" />
                <div>
                  <p className="text-sm font-medium text-blue-800">Academic Excellence</p>
                  <p className="text-2xl font-bold text-blue-900">Certified</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="border-0 shadow-lg bg-gradient-to-br from-green-50 to-green-100">
            <CardContent className="p-6">
              <div className="flex items-center space-x-3">
                <Eye className="h-8 w-8 text-green-600" />
                <div>
                  <p className="text-sm font-medium text-green-800">Official Recognition</p>
                  <p className="text-2xl font-bold text-green-900">Verified</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="border-0 shadow-lg bg-gradient-to-br from-purple-50 to-purple-100">
            <CardContent className="p-6">
              <div className="flex items-center space-x-3">
                <Plus className="h-8 w-8 text-purple-600" />
                <div>
                  <p className="text-sm font-medium text-purple-800">Digital Format</p>
                  <p className="text-2xl font-bold text-purple-900">PDF Ready</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Footer Information */}
        <div className="text-center space-y-2">
          <p className="text-sm text-gray-500">
            Certificates are generated based on final academic year results and attendance records
          </p>
          <p className="text-xs text-gray-400">
            All certificates are digitally signed and include school verification
          </p>
        </div>
      </div>
    </RoleGuard>
  );
};

export default CertificatesModule;
